version: '3'
services:
  db_money_bot:
    image: postgres
    restart: always
    env_file: 
      - .env
    environment:
      POSTGRES_DB: moneybot
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes: 
        - ./pgdata:/var/lib/postgresql/data
    ports: 
      - 5433:5432
    networks: 
        - web
  adminer_money_bot:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - web
  server:
    build: img21326/line_money_bot 
    ports: 
      - 9090:9090
    env_file: 
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:linebotmoneybot.liiao.cc"
      - "traefik.frontend.entryPoints=https,http"
    restart: always
    networks:
        - web
    depends_on:
      - db_money_bot

networks:
  web:
    external: true    
